### PR TITLE
Keep going

### PR DESCRIPTION
**Pull request by pktherock**

### CODE REVIEW

**Comment by SoumyaAgarwal12** [comment]
Thanks for your kind words and comment. Surely I will :)

**Comment by pktherock** [comment]
If you feel comfortable ..can you work together with me and our team..

**Comment by SoumyaAgarwal12** [comment]
What type of work?

**Comment by pktherock** [comment]
we are developing a website on HTML, CSS, JS, JQUERY, BOOTSTRAP, & PHP............................and this is just a project not for money. if you interested then tell me, I will surely contact you

**Comment by SoumyaAgarwal12** [comment]
Okay.....sure

**Comment by pktherock** [comment]
7765811317---you can call or whatsapp on this number

**Comment by SoumyaAgarwal12** [comment]
May we contact on instagram?

**Comment by SoumyaAgarwal12** [comment]
May we contact on Instagram?

**Comment by pktherock** [comment]
Sure.. Insta id.???

**Comment by SoumyaAgarwal12** [comment]
Thank you ☺https://www.instagram.com/_artificial_intelligence_1

**Pull request merged**
